Resolve a circular import of `execute_batch_mode`
Error message:
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/env-dajin2/bin/DAJIN2", line 5, in <module>
    from DAJIN2.main import execute
  File "/home/runner/work/DAJIN2/DAJIN2/src/DAJIN2/main.py", line 20, in <module>
    from DAJIN2 import gui, view
  File "/home/runner/work/DAJIN2/DAJIN2/src/DAJIN2/gui.py", line 16, in <module>
    from DAJIN2.main import execute_batch_mode
ImportError: cannot import name 'execute_batch_mode' from partially initialized module 'DAJIN2.main' (most likely due to a circular import) (/home/runner/work/DAJIN2/DAJIN2/src/DAJIN2/main.py)
DAJIN2 is not installed